language: node_js
node_js:
- node
- '8'
notifications:
  slack:
    secure: MG+jItd+8cYJDfZROlzdLdjq2NMLkTGIyMqGOUsaSPXp1fYwrGIWP2vXWS2m3UaEQjeLxRtGSJSMmM+VRBT/KtkbI2uESEJP3YiKuBwEqYJUQk8wnttk345OmrYAyRsqqekp7QKQGflUWOkEHNQjm+vSxxbX89uZqeAoz+nODlIUZc0s2i0uACazevNblq6krhw5Ss5ssLF4GxG6XkAKg7QrLfi1Ji8pmjB+WVXGpQeYF91qOko85iX14Ej/0aJxTaP19URvaEnk6FVdWCAwQSVJLtGfU90csYx2I0zMSXAi9982s8utMtCXKHscEwYuhoOq3KXshL/PcT0kVy6CTcQvJRu0m4WSKGOHiyQbqgKDXp1unSfOTTDDKXwf2PHZ7h5sDz+xKBMENNV/FGbsnAJAWGb7jjrTZkKrYGC+dr2fwR/9ZCv0NKJRFkIHGXV558bjnUgmk7BQ1e8GBIdtsgq0Y94asQi52PuH2aaoSUNjo+siKfqb+pTaj7jsT2NuPwnB+y9NiPL4MOIKWQuQzg/IaneiZH0OqXPNrQij8MAwFmrq+UEjXrknnJMLWY1xcYx6azVqu/Y+MFeEouuGAnkOo587g1XhynbphPfBM13+PzqZ4597s7WIMXnIAgdtXfxGwbHuvzLT84UIwOmmnrzes2cGjhZJe71xQxf8sbc=
