language: node_js
node_js:
- node
notifications:
  slack:
    secure: U4nA7Ol0BBzBUUtCthGme6SM2HWXIakqKFWwzfRJUEPVSfJQ2kxI+G8Nn+EJQu0mmpTV6VO4zXMtLVoA476h2ycgqk+PHIjBqNmRA9cX4QhT/i/GUqopA0cfUNxhtGmtJj63JBgz2xbdObS4ThqNYCcrsaUoOTMnmLBVzIpFsGKz2EsoGmIB7nY/NPMtEsJi03Tp2vaQNxPHrxDUX73WAdi7+iVq0yQDjnUVEgyiG7YdKjdtOVRxb7WdpnM10N+r0PDcTbndpEQrGqjbIUzPOOviWe+DNIJ6H7FQXC5LAdG4myT/OG/K8zwPMM/QrYkywIn7b2v9CiumZYWVo2z9PBOBa70u6ST/udfuQk4HO0NaY+IK3u6QTyCc8PjXkkqkERuF6qSw4MxdNcjFg8BZ3Ax7i6jx+tp718X20lfevFm2C81NlL7e0ek7L3ZdyYWLLOgObXg67Jqp9JcYMOCba0/bvBrVPAy8MVTKCzmGnPEtdy+tCODju44AU4hbN9yRMGN/k4IpnaR6pao++tcqCUW4qeTeMYg/xIeVdoqIrrj/eg+/tTci7HHWb35lrRDzplR9pUrpjYU1tc2/1slp0ewiRArfbtzqiHvswhfX9K3XltiT78wsCvHSQ2xOF/mvRCcXjux7KfSuxKBgp0niej9iurud/LlGhJvcNwy64E0=
